language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: gijzelaerr
  password:
      secure: "mdz+1zQS49vZk4Shu35Ss72sDdbvg2imT6gDkBqtMHwRgjrOqIFjx1IItQNlAzhaVn+ytko9v4biTpqmlBUIlqP1dscMzimp9brJtXX9zvjThEkzongFlEy2wyuu8DEtwyMYlzDxOSwox27ncXIIILMyPBeH4cvzWYszcNHNv/DUvPQu33v0K3DDL/TuCggR3hPZtrdmc/+AX3nqeqvaPf8bivUD1u4TQLiqyzqlTWnTYoYiknz7Rno0MqshJZoH7cMq8cDC0RiJFuNHlDWq5UCdfEOpKwhatkhRIEJtU98criW3TYvShzjTVobjhGpQ8IDWteAXwM8kUHpqX43OSCim2QduWgL5x1St38nOGN+jQ73woZ6EC9CwdMLuHMLhxqHfaJrYevMc5/yEwHqvBe9olzfhQ+LQsUYgZHMrk4bwXL4ALkTJMCF4K85D/CXSS4tY6KPXBc2Ogro5AQdn5Isf0CisLhEu8dgtyTUqj9vaTzKQmhPs0qFR24L8z9vSPC77qL7yfxw3uF5mmvB3T3VLv5vcV7D7zpo4cbyzzEuBCTmuEYovvQ2qW0tJJWe1vLXbFFd2rnlqee7sIXxUR71YAoDfBNNEJXrggGPuMXaV/vdZrXt/k5jmJAeEUCZL+jlbaidboZsFY0c7u07oYaFJk7sySzowx4PlvU1qPlI="
  on:
    tags: true
