language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: "DvuJUSIb1nraXycSmfmWXRM7UDbVL6D5STPmYLr0Vh+uLXf8R2PBEntsxLGODekTcxlXZ1xrWowl4czk4a5IpQWiYwW23SYd8GAf9U+68oPB6JYJ5swQdaPFyBPu/wC2ZvGvD6H32zuaG2hdvuhCQSwXaStEqRagkAb/aGTr3a+Fs2W4cBQg65TBNBzOREZhS23PpVqUtKA2b2XIUVA2GW1qROFs+9Vh2jmPHL4YMKHERzTf5u52LSPTMidEWd4Qik06MJa4IqVact3cHEnP4mKWDCiGKv/+OKC9kfTpeLanQLVbkWUToF1aQ8MvgxGHO2EvyWMA0wOcKgKK0rlBhfVVOTz7ZPixp5lrxvNTa6iRjoqrQg2GWIB1aPkFP7Q4+D+aDnZLStDFVxsn7EAKbEBy+GTsx3O93jZ//Jo0cOUrc7V39MC0xfuQUIevw56ujfodjPfba9oyQwbR53tEMEU931LsPcI0RfAW9pD8ahQX6MGZLUDeo0nQKLe0SZiMo5dz94mJyqcC0r3LBXUjkCYvhAbAhenUHjLuO5yp0oQLWZuyhp8jJIrTHIv3ul79t1bN/56cqtSlgGceUib0+FQ0Em+nr51KGB2dqun4Lhr93XmUj85LJWG3u5KycZPcjfYra0bZpN4ICeis4TXsZUOUJ/E5GCbnSwXqe6FfoaE="
  on:
    tags: true
